config/routes.rb
Rails.application.routes.draw do
  resources :cliques do
    get 'members'
    get 'administrators'
    get 'requests'
  end
  resources :posts do
    post 'upvote' => 'posts#upvote', as: :upvote
    post 'downvote' => 'posts#downvote', as: :downvote

    resources :comments do
      post 'upvote' => 'comments#upvote', as: :upvote
      post 'downvote' => 'comments#downvote', as: :downvote
    end
  end
  resources :memberships do
    post 'accept' => 'memberships#accept', as: :accept
  end

  resources :users, only: [:show]
  
  root "posts#index"
  devise_for :users, path: '', path_names: { sign_in: 'sign_in', sign_out: 'sign_out', sign_up: 'sign_up' }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable
    acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :get_post
  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = current_user.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.turbo_stream
        # format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        # format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    @comment = Comment.find(params[:comment_id])
    @comment.upvote_from current_user
    respond_to do |format|
      format.html { redirect_to post_comment_url(@post, @comment) }
    end
  end
  
  def downvote
    @comment = Comment.find(params[:comment_id])
    @comment.downvote_from current_user
    respond_to do |format|
      format.html { redirect_to post_comment_url(@post, @comment) }
    end
  end

  def get_post
    @post = Post.find(params[:post_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-4 ml-10">
  <div class="grid grid-cols-12">
    <div class="cols-span-1 ">
      <div class="grid grid-rows-3 justify-items-center">
      <%= button_to "▲", post_comment_upvote_path(@post, comment), method: :post %>
        <%= comment.get_upvotes.size - comment.get_downvotes.size %>
      <%= button_to "▼", post_comment_downvote_path(@post, comment), method: :post %>
      </div>
    </div>
    <div class="cols-span-1">
      <% if @post.clique.members.include?(current_user) || @post.clique.administrators.include?(current_user) %>
        <h4 class="text-sm">u/<%= comment.user.username %></h4>
      <% else %>
        <h4 class="text-sm">u/Anonymous</h4>
      <% end %>
    </div>
  </div>
  <br>
  <p class="text-m"><%= comment.content %></p>
  <%= render "comments/replies" %>
</div>

app/views/comments/_comments.html.erb
<% comments.each do |comment|  %>
  <%= turbo_frame_tag "comment" do %>
    <%= render comment %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= turbo_frame_tag id="new_post_comment" do %>
  <div class="w-full mx-auto mb-10 bg-gray-100 px-5 pb-5 pt-5">
    <%= form_with(model: [@post, comment], class: "contents", data: {'controller': "form", 'action': 'turbo:submit-end->form#clearInputs'}) do |form| %>
      <% if comment.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form.hidden_field :commentable_id, value: commentable.id %>
      <%= form.hidden_field :commentable_type, value: commentable.class.name.demodulize %>
      <div class="ml-10">
        <%= form.text_field :content, class: "mb-5 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "What do you want to say?" %>
      </div>

      <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments", @comment %>

app/views/comments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to 'New comment', new_comment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <%= render @comments %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <%= render "form", comment: @comment, commentable: @post %>
</div>

app/views/comments/show.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <%= turbo_frame_tag "comment" do %>
    <%= render @comment %>
  <% end %>
</div>