config/routes.rb
Rails.application.routes.draw do
  resources :cliques do
    get 'members'
    get 'administrators'
    get 'requests'
  end
  resources :posts do
    post 'upvote' => 'posts#upvote', as: :upvote
    post 'downvote' => 'posts#downvote', as: :downvote

    resources :comments do
      post 'upvote' => 'comments#upvote', as: :upvote
      post 'downvote' => 'comments#downvote', as: :downvote
    end
  end
  resources :memberships do
    post 'accept' => 'memberships#accept', as: :accept
  end

  resources :users, only: [:show]
  
  root "posts#index"
  devise_for :users, path: '', path_names: { sign_in: 'sign_in', sign_out: 'sign_out', sign_up: 'sign_up' }
end

app/models/clique.rb
class Clique < ApplicationRecord
    has_many :memberships, -> { where accepted: true }
    has_many :membership_requests, -> { where accepted: false }, class_name: "Membership"
    has_many :members, through: :memberships, source: :user

    has_many :adminships
    has_many :administrators, through: :adminships, source: :user

    has_many :posts, dependent: :destroy

    validates :title, format: { without: /\s/, message: "Title cannot contain spaces." }


  def update_reputation
    reputation = 0
    self.posts.each do |post|
      reputation += post.cached_votes_score
    end
    self.reputation = reputation
    self.save
  end
end

app/controllers/cliques_controller.rb
class CliquesController < ApplicationController
  before_action :set_clique, only: %i[ show edit update destroy ]

  # GET /cliques or /cliques.json
  def index
    @cliques = current_user.cliques
  end

  # GET /cliques/1 or /cliques/1.json
  def show
    @clique = Clique.find(params[:id])
  end

  # GET /cliques/new
  def new
    @clique = Clique.new
  end

  # GET /cliques/1/edit
  def edit
  end

  # POST /cliques or /cliques.json
  def create
    @clique = Clique.new(clique_params)

    respond_to do |format|
      if @clique.save
        Adminship.create(user: current_user, clique: @clique)
        format.html { redirect_to clique_url(@clique), notice: "Clique was successfully created." }
        format.json { render :show, status: :created, location: @clique }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cliques/1 or /cliques/1.json
  def update
    respond_to do |format|
      if @clique.update(clique_params)
        format.html { redirect_to clique_url(@clique), notice: "Clique was successfully updated." }
        format.json { render :show, status: :ok, location: @clique }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliques/1 or /cliques/1.json
  def destroy
    @clique.destroy

    respond_to do |format|
      format.html { redirect_to cliques_url, notice: "Clique was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def members
    @clique = Clique.find(params[:clique_id])
    @users = @clique.members
  end

  def administrators
    @clique = Clique.find(params[:clique_id])
    @users = @clique.administrators
  end

  def requests
    @clique = Clique.find(params[:clique_id])
    @requests = @clique.membership_requests
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clique
      @clique = Clique.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clique_params
      params.require(:clique).permit(:title, :description)
    end
end

app/helpers/cliques_helper.rb
module CliquesHelper
end

app/views/cliques/_clique.html.erb
<div id="<%= dom_id clique %>">
  <% if action_name != "show" %>
    <%= link_to clique do %>
    <div class="mt-4 ml-5 mr-5">
      <h2 class="text-3xl"><%= clique.title%></h1>
      <div class="mt-2"></div>
      <h4 class="text-1xl"><%= clique.description %></h4>
    </div>
    <% end %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cliques/_form.html.erb
<%= form_with(model: clique, class: "contents") do |form| %>
  <% if clique.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(clique.errors.count, "error") %> prohibited this clique from being saved:</h2>

      <ul>
        <% clique.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :title, class: "mb-5 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Give your Clique a title!" %>
  <%= form.text_field :description, class: "mb-5 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "What is your Clique all about?" %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cliques/_users.html.erb
<div class="w-full">
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>
<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl"><%= @clique.title %></h1>
</div>
<div id="members" class="min-w-full">
    <% @users.each do |user| %>
        <div class="m-5 bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-5 grid grid-cols-3">
          <div class="column">
            <% if user.pfp == nil %>
              <div class="m-2">
                <%= image_tag("nopfp.webp", size: "180x180") %>
              </div>
            <% else %>
              <div class="m-2">
                <%= image_tag(user.pfp) %>
              </div>
            <% end %>
          </div>
          <div class="column">
            <%= link_to user.username, user_path(user), class: "font-bold text-3xl mt-3" %>

            <p class="mt-5">Reputation: <%= user.reputation %></p>
            <p class="mt-2">Posts: <%= user.posts.count %></p>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/cliques/administrators.html.erb
<%= render 'users', users: @administrators %>

app/views/cliques/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing clique</h1>

  <%= render "form", clique: @clique %>

  <%= link_to "Show this clique", @clique, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cliques", cliques_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cliques/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cliques</h1>
    <%= link_to 'Create a Clique!', new_clique_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="cliques" class="min-w-full">
    <%= render @cliques %>
  </div>
</div>

app/views/cliques/members.html.erb
<%= render 'users', users: @members %>

app/views/cliques/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New clique</h1>

  <%= render "form", clique: @clique %>

  <%= link_to 'Back to cliques', cliques_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cliques/requests.html.erb
<div class="w-full">
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>
<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl"><%= @clique.title %> Membership Requests</h1>
</div>
<div id="requests" class="min-w-full">
    <% @requests.each do |request| %>
        <div class="m-5 bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-5 grid grid-cols-3">
          <div class="column">
            <%= link_to request.user.username, user_path(request.user), class: "font-bold text-3xl mt-3" %>
            <p class="mt-5">Reputation: <%= request.user.reputation %></p>
            <p class="mt-2">Posts: <%= request.user.posts.count %></p>
          </div>
          <div class="column">
            <%= button_to "Approve", membership_accept_path(request), method: 'post', class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/cliques/show.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="bg-gray-100 mt-5 mb-5 p-5">
    <div class="grid grid-cols-7">
      <div class="col-span-2">
        <h1 class="text-4xl font-heavy ml-5 mb-5"><%= @clique.title %></h1>
      </div>
      <% if @clique.administrators.include?(current_user) %>
        <%= button_to "Requests", clique_requests_path(@clique), method: :get, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      <% end %>
    </div>

    <div class="mr-5 ml-5">
      <%= @clique.description %>
    </div>
    <div class="grid grid-cols-6 mt-5">
      <div class="col-span-4 m-1">
        <%= button_to "Back", root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      </div>
      <div class="mr-5 m-1">
      <%= button_to "Members", clique_members_path(@clique), method: :get, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      </div>
      <div class="m-1">
      <%= button_to "Administrators", clique_administrators_path(@clique), method: :get, class: "ml-5 rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      </div>
    </div>

    <% unless @clique.members.include?(current_user) || current_user.membership_requests.exists?(clique_id: @clique.id) %>
    <div class="mx-auto">
      <%= render 'memberships/new', membership: Membership.new, clique: @clique %>
    </div>
    <% end %>
  </div>

  <div id="posts" class="min-w-full">
    <% @clique.posts.each do |post| %>
      <%= turbo_frame_tag "post" do %>
        <%= render 'posts/post', post: post %>
      <% end %>
    <% end %>
  </div>

</div>