config/routes.rb
Rails.application.routes.draw do
  resources :cliques do
    get 'members'
    get 'administrators'
    get 'requests'
  end
  resources :posts do
    post 'upvote' => 'posts#upvote', as: :upvote
    post 'downvote' => 'posts#downvote', as: :downvote

    resources :comments do
      post 'upvote' => 'comments#upvote', as: :upvote
      post 'downvote' => 'comments#downvote', as: :downvote
    end
  end
  resources :memberships do
    post 'accept' => 'memberships#accept', as: :accept
  end

  resources :users, only: [:show]
  
  root "posts#index"
  devise_for :users, path: '', path_names: { sign_in: 'sign_in', sign_out: 'sign_out', sign_up: 'sign_up' }
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  validates :content, presence: true
  belongs_to :user
  belongs_to :clique
  has_many :comments, as: :commentable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.sort_by{ |post| post.cached_votes_total + post.user.reputation + post.clique.reputation }.reverse!
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.create(post_params)
    respond_to do |format|
      if @post.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @post = Post.find(params[:post_id])
    @post.upvote_from current_user
    respond_to do |format|
      format.html { redirect_to post_url(@post) }
    end
  end
  
  def downvote
    @post = Post.find(params[:post_id])
    @post.downvote_from current_user
    respond_to do |format|
      format.html { redirect_to post_url(@post) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :clique_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_anonymous_post.html.erb
<div id="<%= dom_id post %>" class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-5">
  <div class="grid grid-cols-12">
    <div class="cols-span-1 ">
      <div class="grid grid-rows-3 justify-items-center">
      <%= button_to "▲", post_upvote_path(post), method: :post %>
        <%= post.get_upvotes.size - post.get_downvotes.size %>
      <%= button_to "▼", post_downvote_path(post), method: :post %>
      </div>
    </div>
    <div class="cols-span-1">
      <h1 class="text-xl"><%= post.title%></h1>
      <h4 class="text-sm">c/Somewhere</h4>
    </div>
  </div>
  <br>
  <p class="text-m"><%= link_to post.content, post_path(post), data: { turbo_frame: "_top" } %></p>

</div>

app/views/posts/_form.html.erb
<%= turbo_frame_tag id="new_post" do %>
  <div class="w-full mx-auto mb-10 bg-gray-100 px-10 pb-10 pt-10">
    <%= form_with(model: post, class: "contents", data: {'controller': "form", 'action': 'turbo:submit-end->form#clearInputs'}) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="ml-10">
        <%= form.select :clique_id, current_user.cliques.collect { |clique| [clique.title, clique.id] }, prompt: "Choose a community" %>
      </div>

      <div class="mt-5">
        <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Add a title!", html: { autocomplete: "off" } %>
      </div>

      <div class="my-5">
        <%= form.text_field :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "What's on your mind?", html: { autocomplete: "off" } %>
      </div>

      <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="bg-gray-100 shadow-md rounded px-8 pt-6 pb-8 mb-5">
  <div class="grid grid-cols-12">
    <div class="cols-span-1 ">
      <div class="grid grid-rows-3 justify-items-center">
      <%= button_to "▲", post_upvote_path(post), method: :post %>
        <%= post.get_upvotes.size - post.get_downvotes.size %>
      <%= button_to "▼", post_downvote_path(post), method: :post %>
      </div>
    </div>
    <div class="cols-span-1">
      <h1 class="text-xl"><%= link_to post.title, post_path(post), data: { turbo_frame: "_top" } %></h1>
      <h4 class="text-sm">c/<%= link_to post.clique.title, clique_path(post.clique), data: { turbo_frame: "_top" } %></h4>
      <% if post.clique.members.include?(current_user) || post.clique.administrators.include?(current_user) %>
        <h4 class="text-sm">u/<%= link_to post.user.username, user_path(post.user), data: { turbo_frame: "_top" } %></h4>
      <% else %>
        <h4 class="text-sm">u/Anonymous</h4>
      <% end %>
    </div>
  </div>
  <br>
  <p class="text-m"><%= link_to post.content, post_path(post), data: { turbo_frame: "_top" } %></p>

</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.append "posts", @post %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "post" do %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Cancel", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <%= button_to "Create a Clique!", new_clique_path, method: "get", class: "mb-5 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
  
  <%= turbo_frame_tag "new_post", src:new_post_path %>
  
  <div id="posts" class="mx-auto md:w-3/3 w-3/3">
    <% @posts.each do |post| %>
      <%= turbo_frame_tag "post" do %>
        <%= render 'post', post: post %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
  <%= link_to 'Back to posts', posts_path, class: "mb-4 rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>

  <%= turbo_frame_tag "post" do %>

    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>
  

  <% end %>
    <% if current_user == @post.user %>
    <%= link_to 'Edit', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium", data: { turbo_frame: "post" } %>

    <div class="inline-block ml-2">
    <%= button_to 'Delete', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-200 font-medium", data: { turbo_frame: "post" } %>
    </div>
    <% end %>
  <% if @post.clique.members.include?(current_user) || @post.clique.administrators.include?(current_user) %>
  <div class="mt-5">
    <%= turbo_frame_tag "new_post_comment", src:new_post_comment_path(@post.id) %>
  </div>
  <% else %>
  <div class="mt-5 mb-5"></div>
  <% end %>

    <div id="comments" class="mt-5">
        <%= render 'comments/comments', comments: @comments %>
    </div>
  </div>
</div>